name: Get Feed

on:
  schedule:
    - cron: '30 12 * * *' # 6pm IST
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
      DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
      RUN_FREQUENCY: 86400 # in seconds
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
      
      - name: Debug current directory
        run: |
          pwd


      - name: Install dependencies
        run: |
          npm ci

      - name: Update Notion Feed
        run: |
          curl -o paperfeed.js https://raw.githubusercontent.com/huanyan0339/paperfeed/master/src/paperfeed.js
          node paperfeed.js
